name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # Note we are using Ubuntu 22.04, here, since this is the latest version
    # that makes Python 3.7 available, see
    # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
    # and we really do want to support Python 3.7
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Note we test Python 3.7 and 3.13, and assume that anything in between
        # will just work.
        python-version: ["3.7", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Lint
      run: |
        ruff check
    - name: Unit tests
      run: |
        pytest