name: Docs

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"
      - name: Build Sphinx documentation
        run: sphinx-build -b html docs _build/html
      - name: Deploy Pages
        uses: actions/deploy-pages@v1
        with:
          path: _build/html
