name: Docs

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install doc dependencies
      run: |
        python -m pip install --upgrade pip
        # se usi pyproject.toml con optional-dependencies
        pip install ".[docs]"
        # oppure, se hai requirements.txt in docs/
        # pip install -r docs/requirements.txt
    - id: deployment
      uses: sphinx-notes/pages@v3
